### ISSUE TITLE
Broken on angular 1.4

### ISSUE THREAD

**Issue by robertbaker** [Luegg/angularjs-scroll-glue#34]
http://plnkr.co/edit/KsUSblFZP6tuVO7UAQMH?p=preview

**Comment by chrismbarr** [comment]
I think this is fixed by #33, correct?

**Comment by robertbaker** [comment]
No my plunkr of the demo references master, still not working

**Comment by Luegg** [comment]
This is not an issue with scroll-glue. Angular 1.4 just broke how controllers are detected initially. I've updated the demo: http://plnkr.co/edit/wxTyp7PpyxJOHSlUumVC?p=preview

**Comment by robertbaker** [comment]
Your demo is not updated.

use this:
    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.0/angular.min.js"></script>
    <script src="https://rawgit.com/Luegg/angularjs-scroll-glue/master/src/scrollglue.js"></script>

Still broken.

**Comment by Luegg** [comment]
Sorry, I've forgot to freeze the plunk. Please try again.
